name: CI
on: [push]
jobs:
  main:
    name: npm test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version:
          - 20
          - 22
          - 24
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - name: install
      run: npm install
    - name: node_js ${{ matrix.version }}
      run: verbose=1 npm test
